github.com:
    users:
        Fais649:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: Fais649
