github.com:
    git_protocol: https
    users:
        Fais649:
            oauth_token: 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
        FaisT2G:
    user: Fais649
    oauth_token: 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
