#!/bin/bash

if [ ! -f "../.config/chromium-flags.conf" ]; then
	cat <<'EOF' > ../.config/chromium-flags.conf
--ozone-platform=wayland
--ozone-platform-hint=wayland
--enable-features=TouchpadOverscrollHistoryNavigation
EOF
fi


if [ ! -f "/etc/chromium-flags.conf" ]; then
sudo cp ../.config/chromium-flags.conf /etc/
fi
